### ISSUE TITLE
README: reformat individual demo docs

### ISSUE THREAD

**Issue by lorinbeer** [SebastianMH/famous-cordova-test#3]
### Issue

multiple projects are documented all form main readme, this could be reformatted to improve readabilty 
### Suggestion:

rather than a master bulleted documentation of dependencies, create toplevel headings for each demo, and discuss dependencies independently.

or

move demo documentation to a www/README.md level file, and only document the presence of the different projects. Link to project level readme in root level README.

**Comment by SebastianMH** [comment]
Thank you for the input.
